- CHANGES
- bin/example.sh
+ add license header on `bin/example.sh` file.
> [S2GRAPH-113] Add license header on `bin/example.sh`

- loader/src/main/scala/org/apache/s2graph/loader/subscriber/TransferToHFile.scala
- s2core/src/main/scala/org/apache/s2graph/core/Edge.scala
- s2core/src/main/scala/org/apache/s2graph/core/JSONParser.scala
- s2core/src/main/scala/org/apache/s2graph/core/Management.scala
- s2core/src/main/scala/org/apache/s2graph/core/PostProcess.scala
- s2core/src/main/scala/org/apache/s2graph/core/mysqls/Label.scala
- s2core/src/main/scala/org/apache/s2graph/core/mysqls/LabelMeta.scala
- s2core/src/main/scala/org/apache/s2graph/core/mysqls/ServiceColumn.scala
- s2core/src/main/scala/org/apache/s2graph/core/parsers/WhereParser.scala
- s2core/src/main/scala/org/apache/s2graph/core/rest/RequestParser.scala
- s2core/src/test/scala/org/apache/s2graph/core/JsonParserTest.scala
- s2rest_netty/src/main/scala/org/apache/s2graph/rest/netty/Server.scala
- s2rest_play/app/org/apache/s2graph/rest/play/controllers/QueryController.scala
+ change JSONParser trait to object.
+ add more helper methods.
> [S2GRAPH-124]: Change JSONParser from Trait to Object.

- s2core/src/main/scala/org/apache/s2graph/core/Edge.scala
- s2core/src/main/scala/org/apache/s2graph/core/Management.scala
- s2core/src/main/scala/org/apache/s2graph/core/mysqls/Label.scala
- s2core/src/main/scala/org/apache/s2graph/core/rest/RequestParser.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/Storage.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/hbase/AsynchbaseStorage.scala
- s2core/src/test/scala/org/apache/s2graph/core/Integrate/WeakLabelDeleteTest.scala
- s2core/src/test/scala/org/apache/s2graph/core/TestCommonWithModels.scala
- s2rest_play/app/org/apache/s2graph/rest/play/controllers/ApplicationController.scala
- s2rest_play/app/org/apache/s2graph/rest/play/controllers/EdgeController.scala
- s2rest_play/app/org/apache/s2graph/rest/play/controllers/PublishController.scala
+ add options variable on label model class.
+ add "skipVertex", "skipReverse" advanced options on `Label`
> [S2GRAPH-125]: Add options field on Label model for controlling advanced options.

- project/Common.scala
- s2core/build.sbt
- s2core/src/main/scala/org/apache/s2graph/core/Edge.scala
- s2core/src/main/scala/org/apache/s2graph/core/Graph.scala
- s2core/src/main/scala/org/apache/s2graph/core/PostProcess.scala
- s2core/src/main/scala/org/apache/s2graph/core/QueryParam.scala
- s2core/src/main/scala/org/apache/s2graph/core/QueryResult.scala
- s2core/src/main/scala/org/apache/s2graph/core/S2Property.scala
- s2core/src/main/scala/org/apache/s2graph/core/S2VertexProperty.scala
- s2core/src/main/scala/org/apache/s2graph/core/mysqls/ColumnMeta.scala
- s2core/src/main/scala/org/apache/s2graph/core/mysqls/Label.scala
- s2core/src/main/scala/org/apache/s2graph/core/mysqls/LabelMeta.scala
- s2core/src/main/scala/org/apache/s2graph/core/parsers/WhereParser.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/Storage.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/hbase/AsynchbaseStorage.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/serde/indexedge/tall/IndexEdgeSerializable.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/serde/indexedge/wide/IndexEdgeSerializable.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/serde/snapshotedge/tall/SnapshotEdgeSerializable.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/serde/snapshotedge/wide/SnapshotEdgeSerializable.scala
- s2core/src/main/scala/org/apache/s2graph/core/types/InnerValLike.scala
- s2core/src/test/scala/org/apache/s2graph/core/Integrate/QueryTest.scala
- s2core/src/test/scala/org/apache/s2graph/core/parsers/WhereParserTest.scala
- s2counter_loader/src/main/scala/org/apache/s2graph/counter/loader/core/CounterEtlFunctions.scala
- s2rest_play/app/org/apache/s2graph/rest/play/controllers/EdgeController.scala
- add tp3 as dependencies.
- make propsWithTs as private.
Note that interface is not implemented on this PR. Few separate issues will be followed up base on this PR.
> [S2GRAPH-129]: Restrict direct access on Edge's properties from other classes.

- .travis.yml
- .travis/hbase.sh
- .travis/install-hbase.sh
- README.md
> [S2GRAPH-108] Support continuous integration test

- .travis.yml
- dev_support/graph_mysql/schema.sql
- s2core/src/main/resources/org/apache/s2graph/core/mysqls/schema.sql
- s2core/src/main/scala/org/apache/s2graph/core/Management.scala
- s2core/src/main/scala/org/apache/s2graph/core/mysqls/GlobalIndex.scala
- s2core/src/main/scala/org/apache/s2graph/core/mysqls/LabelIndex.scala
- update schema file.
- add `GlobalIndex` on models.
- add `buildGlobalIndex` on Management.
- rename `indexOption` into `LabelIndexMutateOption` on LabelIndex class.
> [S2GRAPH-152]: Add buildGlobalIndex API on Management

- build.sbt
- loader/build.sbt
- project/Common.scala
- s2core/src/main/scala/org/apache/s2graph/core/Management.scala
- s2core/src/main/scala/org/apache/s2graph/core/S2Graph.scala
- s2core/src/main/scala/org/apache/s2graph/core/S2GraphFactory.scala
- s2core/src/main/scala/org/apache/s2graph/core/S2Property.scala
- s2core/src/main/scala/org/apache/s2graph/core/rest/RequestParser.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/hbase/AsynchbaseStorage.scala
- s2core/src/main/scala/org/apache/s2graph/core/types/VertexId.scala
- s2core/src/test/scala/org/apache/s2graph/core/Integrate/IntegrateCommon.scala
- s2core/src/test/scala/org/apache/s2graph/core/ManagementTest.scala
- s2core/src/test/scala/org/apache/s2graph/core/tinkerpop/S2GraphProvider.scala
- s2core/src/test/scala/org/apache/s2graph/core/tinkerpop/structure/S2GraphTest.scala
- s2counter_loader/build.sbt
- s2graph_gremlin/README.md
- s2graph_gremlin/build.sbt
- s2graph_gremlin/examples/install_plugin.sh
- s2graph_gremlin/examples/s2graph_getting_started.groovy
- s2graph_gremlin/examples/s2graph_install.groovy
- s2graph_gremlin/examples/s2graph_modern.groovy
- s2graph_gremlin/src/main/resources/META-INF/services/org.apache.tinkerpop.gremlin.groovy.plugin.GremlinPlugin
- s2graph_gremlin/src/main/scala/org/apache/s2graph/core/tinkerpop/groovy/plugin/S2GraphGremlinPlugin.scala
- s2rest_play/app/org/apache/s2graph/rest/play/controllers/AdminController.scala
- add README.md.
- add examples on s2graph_gremlin.
- add java interface for build global index.
- add helper on Management.
- add S2GraphFactory.
- update build.sbt
- add s2graph_gremlin as subproject for gremlin plugin.
- upgrate sbt-assembly.
> [S2GRAPH-148]: Provide Gremlin Plugin

- README.md
- s2core/src/main/scala/org/apache/s2graph/core/mysqls/GlobalIndex.scala
- s2graph_gremlin/README.md
- s2graph_gremlin/src/main/resources/META-INF/services/org.apache.tinkerpop.gremlin.groovy.plugin.GremlinPlugin
- added apache license header on 3 files.
> [S2GRAPH-157]: Check proper apache license header on all files for release 0.2.0

- loader/src/main/scala/org/apache/s2graph/loader/subscriber/TransferToHFile.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/SKeyValue.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/Serializable.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/serde/indexedge/tall/IndexEdgeSerializable.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/serde/indexedge/wide/IndexEdgeSerializable.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/serde/snapshotedge/tall/SnapshotEdgeSerializable.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/serde/snapshotedge/wide/SnapshotEdgeSerializable.scala
- s2core/src/main/scala/org/apache/s2graph/core/types/v2/InnerVal.scala
- s2rest_play/app/org/apache/s2graph/rest/play/controllers/ApplicationController.scala
- add charsetName as `UTF-8` on String.getBytes.
> [S2GRAPH-158]: Bug fix on String type InnerVal encoding to use UTF-8 charsetName.

- s2core/src/main/scala/org/apache/s2graph/core/ExceptionHandler.scala
- s2core/src/main/scala/org/apache/s2graph/core/JSONParser.scala
- s2core/src/main/scala/org/apache/s2graph/core/Management.scala
- s2core/src/main/scala/org/apache/s2graph/core/QueryResult.scala
- s2core/src/main/scala/org/apache/s2graph/core/S2Edge.scala
- s2core/src/main/scala/org/apache/s2graph/core/S2Graph.scala
- s2core/src/main/scala/org/apache/s2graph/core/S2GraphFactory.scala
- s2core/src/main/scala/org/apache/s2graph/core/S2Property.scala
- s2core/src/main/scala/org/apache/s2graph/core/mysqls/Bucket.scala
- s2core/src/main/scala/org/apache/s2graph/core/mysqls/Label.scala
- s2core/src/main/scala/org/apache/s2graph/core/rest/RequestParser.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/SKeyValue.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/Storage.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/hbase/AsynchbaseStorage.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/serde/indexedge/tall/IndexEdgeDeserializable.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/serde/indexedge/wide/IndexEdgeDeserializable.scala
- s2rest_netty/src/main/scala/org/apache/s2graph/rest/netty/Server.scala
- s2rest_play/app/org/apache/s2graph/rest/play/Bootstrap.scala
- s2rest_play/app/org/apache/s2graph/rest/play/controllers/AdminController.scala
- s2rest_play/app/org/apache/s2graph/rest/play/controllers/EdgeController.scala
- fix warnings from comments.
- fix warnings from tuple.
- fix type parameter name collision with tinkerpop.T.
> [S2GRAPH-160]: Remove warning while package

- NOTICE
- update year from 2016 to 2017
> [S2GRAPH-162]: Update year in the NOTICE file.

- s2graph_gremlin/examples/s2graph_install.groovy
- version.sbt
- update version to 0.2.1-SNAPSHOT.
> [S2GRAPH-163]: Update version.sbt after release

- README.md
- update README to contains tinkerpop support.
> [S2GRAPH-165]: Add TinkerPop support documentation on README

- s2core/build.sbt
- s2core/src/main/resources/rocks_storage.conf
- s2core/src/main/scala/org/apache/s2graph/core/S2Graph.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/StorageReadable.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/hbase/AsynchbaseStorageReadable.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/rocks/RocksHelper.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/rocks/RocksStorage.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/rocks/RocksStorageManagement.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/rocks/RocksStorageReadable.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/rocks/RocksStorageSerDe.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/rocks/RocksStorageWritable.scala
- s2core/src/test/scala/org/apache/s2graph/core/Integrate/QueryTest.scala
- s2core/src/test/scala/org/apache/s2graph/core/storage/rocks/RocksStorageTest.scala
> [S2GRAPH-166]: Provide embeddable storage backend using RocksDB 

- s2core/src/main/scala/org/apache/s2graph/core/Management.scala
- s2core/src/main/scala/org/apache/s2graph/core/mysqls/ColumnMeta.scala
- s2core/src/main/scala/org/apache/s2graph/core/mysqls/Service.scala
- s2core/src/main/scala/org/apache/s2graph/core/mysqls/ServiceColumn.scala
- s2graphql/src/main/resources/application.conf
- s2graphql/src/main/scala/GraphQLServer.scala
- s2graphql/src/main/scala/GraphRepository.scala
- s2graphql/src/main/scala/S2Type.scala
- add createServiceColumn.
- add addVertex.
> [S2GRAPH-177]: Add support for createServiceColumn/addVertex APIs on GraphQL.

- loader/build.sbt
- loader/loader.py
- loader/src/main/scala/org/apache/s2graph/loader/spark/HBaseContext.scala
- loader/src/main/scala/org/apache/s2graph/loader/spark/HBaseRDDFunctions.scala
- loader/src/main/scala/org/apache/s2graph/loader/subscriber/GraphSubscriber.scala
- loader/src/main/scala/org/apache/s2graph/loader/subscriber/TransferToHFile.scala
- loader/src/test/scala/org/apache/s2graph/loader/subscriber/TransferToHFileTest.scala
- s2core/src/main/scala/org/apache/s2graph/core/JSONParser.scala
- s2core/src/main/scala/org/apache/s2graph/core/mysqls/ServiceColumn.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/SKeyValue.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/StorageSerDe.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/hbase/AsynchbaseStorageManagement.scala
- call apply to initialize Graph/Management on `GraphSubscriberHelper` object.
> [S2GRAPH-178]: Fix null pointer error on BulkLoader.

- s2core/src/main/scala/org/apache/s2graph/core/S2Graph.scala
- s2core/src/main/scala/org/apache/s2graph/core/S2VertexPropertyHelper.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/SKeyValue.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/hbase/AsynchbaseStorageManagement.scala
- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/DegreeKey.scala
- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/S2GraphHelper.scala
- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/loader/HFileGenerator.scala
- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/loader/HFileMRGenerator.scala
- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/loader/LocalBulkLoaderTransformer.scala
- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/loader/SparkBulkLoaderTransformer.scala
- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/serde/GraphElementReadable.scala
- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/serde/GraphElementWritable.scala
- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/serde/Transformer.scala
- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/serde/reader/TsvBulkFormatReader.scala
- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/serde/writer/KeyValueWriter.scala
- s2jobs/src/test/scala/org/apache/s2graph/s2jobs/BaseSparkTest.scala
- s2jobs/src/test/scala/org/apache/s2graph/s2jobs/dump/GraphFileDumperTest.scala
- s2jobs/src/test/scala/org/apache/s2graph/s2jobs/loader/GraphFileGeneratorTest.scala
- abstract read/write of user provided class.
> [S2GRAPH-183]: Provide batch job to dump data stored in HBase into file.

- example/movielens/README.md
- add REAME.md to explaining movielens example.
> [S2GRAPH-214]: Add REAME for movielens examples

- s2core/src/main/scala/org/apache/s2graph/core/TraversalHelper.scala
- s2core/src/main/scala/org/apache/s2graph/core/fetcher/annoy/AnnoyModelFetcher.scala
- s2core/src/main/scala/org/apache/s2graph/core/fetcher/fasttext/FastTextFetcher.scala
- s2core/src/main/scala/org/apache/s2graph/core/fetcher/tensorflow/InceptionFetcher.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/StorageIO.scala
- Extract Where and EdgeTransformer to TraversalHelper.
> [S2GRAPH-220]: Filter clause is not working on AnnoyModelFetcher

- s2core/src/main/scala/org/apache/s2graph/core/parsers/WhereParser.scala
- s2core/src/test/scala/org/apache/s2graph/core/parsers/WhereParserTest.scala
> [S2GRAPH-222]: Support Not logical operator in WhereParser.

- CHANGES
- s2core/src/main/scala/org/apache/s2graph/core/QueryParam.scala
- s2core/src/main/scala/org/apache/s2graph/core/S2EdgePropertyHelper.scala
- s2core/src/main/scala/org/apache/s2graph/core/S2Graph.scala
- s2core/src/main/scala/org/apache/s2graph/core/S2GraphLike.scala
- s2core/src/main/scala/org/apache/s2graph/core/VertexFetcher.scala
- s2core/src/main/scala/org/apache/s2graph/core/index/ESIndexProvider.scala
- s2core/src/main/scala/org/apache/s2graph/core/index/LuceneIndexProvider.scala
- s2core/src/main/scala/org/apache/s2graph/core/parsers/WhereParser.scala
- s2core/src/main/scala/org/apache/s2graph/core/rest/RequestParser.scala
- s2core/src/main/scala/org/apache/s2graph/core/rest/RestHandler.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/hbase/AsynchbaseStorage.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/hbase/AsynchbaseVertexFetcher.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/rocks/RocksVertexFetcher.scala
- s2core/src/test/scala/org/apache/s2graph/core/Integrate/VertexTestHelper.scala
- s2core/src/test/scala/org/apache/s2graph/core/index/IndexProviderTest.scala
- s2core/src/test/scala/org/apache/s2graph/core/parsers/WhereParserTest.scala
- s2graphql/src/main/scala/org/apache/s2graph/graphql/types/FieldResolver.scala
- Refactor WhereParser to accept GraphElement.
- Refactor S2Graph.getVertices to accept VertexQueryParam.
> [S2GRAPH-223]: Support WhereParser on Vertex.

- project/Common.scala
> [S2GRAPH-227]: version up SLF4J bindings(slf4j-log4j12) from 1.7.21 to 1.8.0-beta2
