- s2core/build.sbt
- s2core/src/main/scala/org/apache/s2graph/core/storage/hbase/AsynchbasePatcher.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/hbase/AsynchbaseStorage.scala
This commit adds `object AsynchbasePatcher`, which patches Asynchbase's `Scanner` class before its loading, to make it a non-final class, and uses ByteBuddy to dynamically create a subclass of `Scanner` that supports an RPC-level timeout support, by adding a bean property `int rpcTimeout` and overriding `getNextRowsRequest()`.
> [S2GRAPH-116] using ASM and ByteBuddy to add a proxy to Asynchbase's Scanner

- build.sbt
- project/Publisher.scala
- version.sbt
Now SBT will add the necessary XMLs to the POM being published, to meet the requirements of ASF and Maven Central.
Additionally, the version is now stored in `version.sbt`, to follow the conventions of sbt-release-plugin.
All subprojects are now configured to be published, and if that is not necessary we can configure to publish only a subset of the subprojects.
> [S2GRAPH-115] ready to upload the binary artifacts to Maven Central

- CHANGES
- project/Publisher.scala
Now `credentials` will be empty when settings.xml does not exist.
> [S2GRAPH-126] fixes SBT error that occurs if ~/.m2/settings.xml does not exist

- loader/src/main/scala/org/apache/s2graph/loader/subscriber/GraphSubscriber.scala
- loader/src/main/scala/org/apache/s2graph/loader/subscriber/TransferToHFile.scala
- loader/src/main/scala/org/apache/s2graph/loader/subscriber/WalLogStat.scala
- loader/src/main/scala/org/apache/s2graph/loader/subscriber/WalLogToHDFS.scala
- s2core/src/main/scala/org/apache/s2graph/core/Edge.scala
- s2core/src/main/scala/org/apache/s2graph/core/Graph.scala
- s2core/src/main/scala/org/apache/s2graph/core/QueryParam.scala
- s2core/src/main/scala/org/apache/s2graph/core/QueryResult.scala
- s2core/src/main/scala/org/apache/s2graph/core/S2Property.scala
- s2core/src/main/scala/org/apache/s2graph/core/S2VertexProperty.scala
- s2core/src/main/scala/org/apache/s2graph/core/Vertex.scala
- s2core/src/main/scala/org/apache/s2graph/core/mysqls/ServiceColumn.scala
- s2core/src/main/scala/org/apache/s2graph/core/rest/RequestParser.scala
- s2core/src/main/scala/org/apache/s2graph/core/rest/RestHandler.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/Storage.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/serde/indexedge/tall/IndexEdgeDeserializable.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/serde/indexedge/wide/IndexEdgeDeserializable.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/serde/snapshotedge/tall/SnapshotEdgeDeserializable.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/serde/snapshotedge/wide/SnapshotEdgeDeserializable.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/serde/vertex/VertexDeserializable.scala
- s2core/src/main/scala/org/apache/s2graph/core/types/VertexId.scala
- s2core/src/test/scala/org/apache/s2graph/core/EdgeTest.scala
- s2core/src/test/scala/org/apache/s2graph/core/Integrate/IntegrateCommon.scala
- s2core/src/test/scala/org/apache/s2graph/core/Integrate/QueryTest.scala
- s2core/src/test/scala/org/apache/s2graph/core/Integrate/WeakLabelDeleteTest.scala
- s2core/src/test/scala/org/apache/s2graph/core/benchmark/GraphUtilSpec.scala
- s2core/src/test/scala/org/apache/s2graph/core/parsers/WhereParserTest.scala
- s2core/src/test/scala/org/apache/s2graph/core/storage/hbase/IndexEdgeTest.scala
- s2counter_loader/src/main/scala/org/apache/s2graph/counter/loader/core/CounterEtlFunctions.scala
- version.sbt
- Change data type of Edge.propsWithTs to java.util.Map.
- Make Vertex/Edge/Graph to implement Tinkerpop3 structure interface.
Note that this PR based on #99 PR.
> [S2GRAPH-130]: Edge.propsWithTs data type should be changed into mutable to support setter interface exist in tp3.	

- s2core/src/main/scala/org/apache/s2graph/core/S2Edge.scala
- s2core/src/main/scala/org/apache/s2graph/core/mysqls/LabelIndex.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/Storage.scala
- s2core/src/test/scala/org/apache/s2graph/core/Integrate/IntegrateCommon.scala
- s2core/src/test/scala/org/apache/s2graph/core/Integrate/LabelIndexOptionTest.scala
I changed the functionality of 'labelIndexOption' as described in {{S2GRAPH-135}} issue.
When this PR is merged, you can set different options for each direction(in, out) through the 'options' field in 'LabelIndex' table.
> [S2GRAPH-135] Change the way LabelIndexOption is implemented and improve it

- s2core/src/main/scala/org/apache/s2graph/core/S2Edge.scala
- s2core/src/main/scala/org/apache/s2graph/core/S2Graph.scala
- s2core/src/main/scala/org/apache/s2graph/core/mysqls/LabelIndex.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/Storage.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/hbase/AsynchbaseStorage.scala
- s2core/src/test/scala/org/apache/s2graph/core/Integrate/IntegrateCommon.scala
- s2core/src/test/scala/org/apache/s2graph/core/Integrate/LabelIndexOptionTest.scala
This feature will reduce the number of RPCs delivered to each region and will therefore improve increment performance.
I've discovered a few issues while adding this feature.
The data on the Edge has changed where i did not expected it.
It appears that the Edge class has been changed to a mutable.
To solve this problem, I used a deepCopied of the Edge where i created the RPC
I would like to discuss this in another thread to find a more fundamental cause.
> [S2GRAPH-132] Added the ability to buffer write rpc for increment requests.

- s2rest_play/app/org/apache/s2graph/rest/play/controllers/AdminController.scala
S2GRAPH-168 - Fix args order mismatch when use addServiceColumnProp
> [S2GRAPH-168]:Fix args order mismatch when use addServiceColumnProp

- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/loader/GraphFileGenerator.scala
Spark driver exit abnormally  and yarn would retry 3 times in s2jobs class  org.apache.s2graph.s2jobs.loader.GraphFileGenerator. Driver report ：
ApplicationMaster: Final app status: FAILED, exitCode: 16, (reason: Shutdown hook called before final status was reported.)
Which cause by  System.exit(0) in GraphFileGenerator.scala before sc.stop() was called.
fix https://issues.apache.org/jira/browse/S2GRAPH-184
> [S2GRAPH-184]: fix spark driver exit abnormally bug

- project/Common.scala
- s2jobs/build.sbt
- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/Job.scala
- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/JobDescription.scala
- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/JobLauncher.scala
- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/Logger.scala
- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/Schema.scala
- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/task/Process.scala
- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/task/Sink.scala
- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/task/Source.scala
- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/task/Task.scala
- s2jobs/src/main/scala/org/apache/s2graph/spark/sql/streaming/Logger.scala
- s2jobs/src/main/scala/org/apache/s2graph/spark/sql/streaming/S2CommitProtocol.scala
- s2jobs/src/main/scala/org/apache/s2graph/spark/sql/streaming/S2SinkConfigs.scala
- s2jobs/src/main/scala/org/apache/s2graph/spark/sql/streaming/S2SinkContext.scala
- s2jobs/src/main/scala/org/apache/s2graph/spark/sql/streaming/S2SinkMetadataLog.scala
- s2jobs/src/main/scala/org/apache/s2graph/spark/sql/streaming/S2SinkProvider.scala
- s2jobs/src/main/scala/org/apache/s2graph/spark/sql/streaming/S2SinkStatus.scala
- s2jobs/src/main/scala/org/apache/s2graph/spark/sql/streaming/S2SparkSqlStreamingSink.scala
- s2jobs/src/main/scala/org/apache/s2graph/spark/sql/streaming/S2StreamQueryWriter.scala
- s2jobs/src/test/scala/org/apache/s2graph/s2jobs/task/ProcessTest.scala
I added a simple job launcher using spark structured streaming, which consists of three parts: source, process, and sink.
The source and sink can use the built-in types supported by structured streaming and can be added using the type provided by the 3rd party or by directly implementing.
For data processing, provide SQLProcess using SparkSql and udf, and can implement custom class if necessary.
* kakfa : built-in
* file : built-in
* hive : built-in
* sql : process spark sql
* custom : implement if necessary
* kafka : built-in
* file : built-in
* es : elasticsearch-spark
* s2graph : added
* Use the mutateElement function of the S2graph object.
* S2graph related setting is required.
* put the config file in the classpath or specify it in the job description options.
```
ex)
"type": …
```
> [S2GRAPH-185] Support Spark Structured Streaming

- s2graphql/src/main/scala/org/apache/s2graph/graphql/types/S2ManagementType.scala
- s2graphql/src/test/scala/org/apache/s2graph/graphql/SchemaTest.scala
There was a bug in naming collision when 'sourceService' and 'targetService' types of 'Argument' used in 'CreateLabel' type were created.
In GraphQL rules, 'ObjectType' has to have unique name inside schema, but when service is more than 2, it has not got name for each service.
> [S2GRAPH-192] could not find service column when creating the label 

- project/Common.scala
- s2graphql/src/main/scala/org/apache/s2graph/graphql/GraphQLServer.scala
- s2graphql/src/main/scala/org/apache/s2graph/graphql/HttpServer.scala
- s2graphql/src/main/scala/org/apache/s2graph/graphql/repository/GraphRepository.scala
1. I removed the dependency by adding `ExclusionRule (" org.apache.logging.log4j "," log4j-slf4j-impl ")` to `Common.scala` to fix` multiple_binding` error.
```bash
s2graphql[ERROR] SLF4J: Class path contains multiple SLF4J bindings.
s2graphql[ERROR] SLF4J: Found binding in [jar:file:/Users/daewon/.ivy2/cache/org.apache.logging.log4j/log4j-slf4j-impl/jars/log4j-slf4j-impl-2.9.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
s2graphql[ERROR] SLF4J: Found binding in [jar:file:/Users/daewon/.ivy2/cache/org.slf4j/slf4j-log4j12/jars/slf4j-log4j12-1.7.21.jar!/org/slf4j/impl/StaticLoggerBinder.class]
s2graphql[ERROR] SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
s2graphql[ERROR] SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory] …
```
> [S2GRAPH-191] Providing request / response logging to GraphQL server and removing println

- s2core/src/main/scala/org/apache/s2graph/core/rest/RequestParser.scala
- s2core/src/test/scala/org/apache/s2graph/core/Integrate/IntegrateCommon.scala
- s2core/src/test/scala/org/apache/s2graph/core/Integrate/VertexTestHelper.scala
- refactor `toVertex` to be shared on `toQuery`.
- add a test case on VertexTestHelper(escaping of double quotation marks).
> [S2GRAPH-187]: Make toQuery use toVertex to parse vertex from query JSON on RequestParser

- s2graphql/src/main/scala/org/apache/s2graph/graphql/types/S2ManagementType.scala
- s2graphql/src/main/scala/org/apache/s2graph/graphql/types/S2Type.scala
- s2graphql/src/main/scala/org/apache/s2graph/graphql/types/package.scala
Fixed where `label  \ indices` resolver would return `Nil` unconditionally
> [S2GRAPH-195] could not create indices using S2GraphQL

- build.sbt
- dev_support/README.md
- project/plugins.sbt
- s2rest_netty/build.sbt
- s2rest_play/build.sbt
Currently, we support to build docker image through docker plugin of sbt-native-packager.
When packaging with the native-packager, the generated executable scripts add only the jars in the lib directory to the classpath.
```
//  default application structure
bin/
<app_name>       <- BASH script
<app_name>.bat   <- cmd.exe script
lib/
<Your project and dependent jar files here.>
```
I added some command to copy extra jar on the classpath, in the executable scripts
When launching docker image, if we need to add extra jars in classpath, we could use environment variable 'EXTRA_JARS'
ex) 
```
docker run --name s2graph -v /LocalJarsDir:/extraJars -e EXTRA_JARS=/extraJars -dit s2graph/s2graphql:latest ...
```
Additionally, I used the [sbt-docker …
> [S2Graph-200]  add extra jar in classpath dynamically when launching docker image

- s2graphql/src/main/scala/org/apache/s2graph/graphql/GraphQLServer.scala
- s2graphql/src/main/scala/org/apache/s2graph/graphql/repository/GraphRepository.scala
- s2graphql/src/main/scala/org/apache/s2graph/graphql/types/ManagementType.scala
- s2graphql/src/main/scala/org/apache/s2graph/graphql/types/S2Type.scala
- s2graphql/src/test/scala/org/apache/s2graph/graphql/TestGraph.scala
I removed the part where 'N + 1' queries occur in queries that fetch Vertices and Edges using 'DeferredResolver' provided by sangria framework.
http://sangria-graphql.org/learn/#deferred-value-resolution
> [S2GRAPH-204] Avoid N + 1 queries in GraphQL

- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/S2GraphHelper.scala
- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/loader/LocalBulkLoaderTransformer.scala
- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/loader/SparkBulkLoaderTransformer.scala
- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/task/Sink.scala
- s2jobs/src/main/scala/org/apache/s2graph/spark/sql/streaming/S2SinkContext.scala
- s2jobs/src/main/scala/org/apache/s2graph/spark/sql/streaming/S2StreamQueryWriter.scala
- s2jobs/src/test/scala/org/apache/s2graph/s2jobs/BaseSparkTest.scala
- s2jobs/src/test/scala/org/apache/s2graph/s2jobs/S2GraphHelperTest.scala
- s2jobs/src/test/scala/org/apache/s2graph/s2jobs/loader/GraphFileGeneratorTest.scala
I replaced S2GraphHeler.initS2graph method to getS2Graph that reuse created an S2Graph object
> [S2GRAPH-205] reuse S2Graph object on same executor

- s2core/src/main/scala/org/apache/s2graph/core/QueryParam.scala
- s2core/src/main/scala/org/apache/s2graph/core/S2Graph.scala
- s2core/src/main/scala/org/apache/s2graph/core/index/ESIndexProvider.scala
- s2core/src/main/scala/org/apache/s2graph/core/index/IndexProvider.scala
- s2core/src/main/scala/org/apache/s2graph/core/index/LuceneIndexProvider.scala
- s2core/src/main/scala/org/apache/s2graph/core/parsers/WhereParser.scala
- s2core/src/main/scala/org/apache/s2graph/core/rest/RequestParser.scala
- s2core/src/test/scala/org/apache/s2graph/core/Integrate/QueryTest.scala
- s2core/src/test/scala/org/apache/s2graph/core/index/IndexProviderTest.scala
- s2core/src/test/scala/org/apache/s2graph/core/parsers/WhereParserTest.scala
- s2graphql/src/main/scala/org/apache/s2graph/graphql/repository/GraphRepository.scala
- s2graphql/src/main/scala/org/apache/s2graph/graphql/types/FieldResolver.scala
- s2graphql/src/main/scala/org/apache/s2graph/graphql/types/S2Type.scala
- s2graphql/src/test/scala/org/apache/s2graph/graphql/ScenarioTest.scala
You can use the 'apache [lucene](https://lucene.apache.org) query' directly in the 'search' parameter to search vertex by property values
example)
{noformat}
```graphql
{
kakao {
user(search: "gender: M OR gender: F") {
id
age
gender
}
}
}
```
{noformat}
{noformat}
```graphql
{
kakao {
user(search: "age: 19 OR age: 20") {
id
age
gender
}
}
}
```
{noformat}
> [S2GRAPH-207] Provides a way to query data with the value of the Vertex property in a GraphQL query.

- s2core/src/main/scala/org/apache/s2graph/core/QueryParam.scala
- s2core/src/main/scala/org/apache/s2graph/core/index/ESIndexProvider.scala
- s2core/src/main/scala/org/apache/s2graph/core/index/LuceneIndexProvider.scala
- s2graphql/src/test/scala/org/apache/s2graph/graphql/ScenarioTest.scala
First implemented a range query in 'elasticsearch' and applied VertexQueryParam(offset, limit).
> [S2GRAPH-209] GlobalIndex supports field data types such as Numeric to enable Range Query.

- s2core/src/main/scala/org/apache/s2graph/core/EdgeFetcher.scala
- s2core/src/main/scala/org/apache/s2graph/core/EdgeMutator.scala
- s2core/src/main/scala/org/apache/s2graph/core/Management.scala
- s2core/src/main/scala/org/apache/s2graph/core/ResourceManager.scala
- s2core/src/main/scala/org/apache/s2graph/core/S2Graph.scala
- s2core/src/main/scala/org/apache/s2graph/core/VertexFetcher.scala
- s2core/src/main/scala/org/apache/s2graph/core/VertexMutator.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/jdbc/JdbcEdgeFetcher.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/jdbc/JdbcEdgeMutator.scala
- s2core/src/main/scala/org/apache/s2graph/core/storage/jdbc/JdbcStorage.scala
- s2core/src/main/scala/org/apache/s2graph/core/utils/Importer.scala
- s2core/src/main/scala/org/apache/s2graph/core/utils/SafeUpdateCache.scala
- s2core/src/test/scala/org/apache/s2graph/core/fetcher/BaseFetcherTest.scala
- s2core/src/test/scala/org/apache/s2graph/core/storage/jdbc/JdbcStorageTest.scala
- s2graphql/src/test/scala/org/apache/s2graph/graphql/TestGraph.scala
I chose the H2 DB(org.h2.Drvier) as the JDBC Driver implementation.
The current implementation is to work for each Label according to the Label option.
I plan to move to the storage level later.
```json
{
"fetcher": {
"className": "org.apache.s2graph.core.storage.jdbc.JdbcEdgeFetcher",
"url": "jdbc:h2:file:/tmp/s2graph/metastore;MODE=MYSQL",
"driver": "org.h2.Driver",
"password": "sa",
"user": "sa"
},
"mutator": {
"className": "org.apache.s2graph.core.storage.jdbc.JdbcEdgeMutator",
"url": "jdbc:h2:file:/tmp/s2graph/metastore;MODE=MYSQL",
"driver": "org.h2.Driver",
"password": "sa",
"user": "sa"
}
}
```
- Basic Edge CRUD with Strong, Weak consistency option.  
- Implement VertexMutator, VertexFetcher
- Other JDBC support, including PostgreSQL
> [S2GRAPH-215] Implement a Storage Backend for JDBC driver, such as H2, MySql using the Mutator and Fetcher interfaces.

- build.sbt
- s2core/build.sbt
- s2graphql/build.sbt
- s2graphql/src/main/scala/org/apache/s2graph/graphql/GraphQLServer.scala
- s2graphql/src/main/scala/org/apache/s2graph/graphql/middleware/Transform.scala
- s2graphql/src/main/scala/org/apache/s2graph/graphql/types/FieldResolver.scala
- s2graphql/src/main/scala/org/apache/s2graph/graphql/types/S2Directive.scala
- s2graphql/src/main/scala/org/apache/s2graph/graphql/types/SchemaDef.scala
- s2graphql/src/test/scala/org/apache/s2graph/graphql/DirectiveTest.scala
I Implemented the string manipulation using the `scala.tools`.  
The code(scala) to be created must be a function that takes a 'String' as an argument and returns a 'String'.
Here is a query that appends `prefix_` to the `label` column.
```sql
select concat ('prefix_', label) as with_prefix from labels limit 2
```
Here is an example of writing a function that supports the above functions in SQL.
```graphql
{
   labels {
     label @transform (func: "(s: String) => \" prefix \ _ "+ s") # scala anonymous function
   }
}
```
> [S2GRAPH-216] Provide a transform directive in the GraphQL query result

- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/Job.scala
- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/task/Process.scala
- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/task/Sink.scala
- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/task/Source.scala
- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/task/Task.scala
I have added some operations that are not represented in spark SQL.
* Windowed Grouped Aggregations : grouped.*
* Watermark : watermark.delay.time, time.column
* Streaming Deduplication : drop.duplicate.columns
* dataframe cache option : cache
* Continuous Streaming : isContinuous
```
{
"name": "category_distinct",
"inputs": [
"category_bulk"
],
"type": "sql",
"options": {
"sql": "SELECT url, category FROM category_bulk",
"drop.duplicate.columns": "url,category"     // deduplicate
}
"cache": "true"   // cache (only support not streaming dataframe)
},
{
"name": "grouped",
"inputs": [
"demo_join"
],
"type": "sql",
"options": {
"sql": "SELECT * FROM demo_join",
"watermark.delay.time": "1 minutes",                      // watermark
"time.column": "ts",
"grouped.keys": "age_band, gender, …
```
> [S2GRAPH-218] add operations not supported on sql

- s2graphql/src/main/scala/org/apache/s2graph/graphql/GraphQLServer.scala
- s2graphql/src/main/scala/org/apache/s2graph/graphql/middleware/GraphFormatWriter.scala
- s2graphql/src/main/scala/org/apache/s2graph/graphql/middleware/SigmaJS.scala
- s2graphql/src/main/scala/org/apache/s2graph/graphql/repository/GraphRepository.scala
- s2graphql/src/main/scala/org/apache/s2graph/graphql/types/PlayJsonScalarType.scala
I added a functionality a data format that includes Vertices, Edges in the GraphQL query results .
The data format is similar to [GraphSON](http://tinkerpop.apache.org/docs/current/reference/#graphson-io-format)
The data format for embedding the Graph is very similar, so it would be very useful for testing Visualize tools such as [sigma.js](http://sigmajs.org/) and graph algorithms.
Perform a general query as shown below.
Include "includeGraph" in the query variable below.
- Query Variable
```json
{
"includeGraph": true
}
```
- Query 
```graphql
{
kakao {
user(ids: ["daewon", "shon"]) {
id
age
gender
inFriends: friends(direction: in, limit: 3) {
user {
id
}
}
}
}
}
```
As you can see in the above query, you can see that the graph has a `graph` key under the `extensions` entry with the …
> [S2GRAPH-219] Added query that includes all vertices and associated edges for GraphVisualize.

- s2graphql/src/main/scala/org/apache/s2graph/graphql/GraphQLServer.scala
- s2graphql/src/main/scala/org/apache/s2graph/graphql/HttpServer.scala
I added the ability to allow the GraphQL server to interpret the `application/graphql` content-type. 
no longer need to escape the `graphql query string` to a `json string`
example)
```bash
curl --request POST \                                                                           
--url http://localhost:8000/graphql \
--header 'content-type: application/graphql' \
--data 'query Welcome {
kakao {
user(id: "daewon") {
id
}
}
}'
```
> [S2GRAPH-203] Support "application/graphql" Content-Type header

- .gitignore
- s2core/build.sbt
- s2core/src/main/scala/org/apache/s2graph/core/step/IStep.scala
- s2core/src/test/scala/org/apache/s2graph/core/step/GraphStepTest.scala
- s2core/src/test/scala/org/apache/s2graph/core/step/StepTest.scala
I have created an interface for each step to enable query combinations(using Observable[T])
```scala
trait RxStep[-A, +B] extends (A => Observable[B])
```
RxStep simply inherits the function interface (A => B)
This makes it possible to naturally connect with the transform functions provided by Observable (map, flatMap ..)
I have implemented a simple query in the `GraphTest.scala` file for the step utilization test.
Here is the example code.
'VertexFetchStep' and 'EdgeFetchStep' each implement RxStep trait.
In addition, since GraphElement => Boolean is implemented in 'Where', it naturally integrates with Observable interface.
```scala
val v1 = VertexFetchStep(graph)
val qpIn = QueryParam(labelName = testLabelName, direction = "in")
val qpOut = QueryParam(labelName = testLabelName, …
```
> [S2GRAPH-229] 'Step' abstraction for combinable queries

- s2core/src/main/scala/org/apache/s2graph/core/ResourceManager.scala
- s2core/src/main/scala/org/apache/s2graph/core/S2Graph.scala
- s2core/src/main/scala/org/apache/s2graph/core/utils/SafeUpdateCache.scala
- add background task on ResourceManager onEvict.
> [S2GRAPH-230]: ResourceManager onEvict cause segmentation fault with AnnoyModelFetcher

- s2core/src/main/scala/org/apache/s2graph/core/schema/ColumnMeta.scala
- s2core/src/main/scala/org/apache/s2graph/core/schema/LabelIndex.scala
- s2graphql/src/main/scala/org/apache/s2graph/graphql/GraphQLServer.scala
- s2graphql/src/main/scala/org/apache/s2graph/graphql/HttpServer.scala
- s2graphql/src/main/scala/org/apache/s2graph/graphql/repository/GraphRepository.scala
- s2graphql/src/main/scala/org/apache/s2graph/graphql/types/ManagementType.scala
- s2graphql/src/main/scala/org/apache/s2graph/graphql/types/S2Type.scala
- s2graphql/src/main/scala/org/apache/s2graph/graphql/types/SchemaDef.scala
When I created an issue, I expected that there would be a load on duplicate ObjectType generation.
However, the profiling result was actually a lot of DB round trips in the bottleneck area.
For example, to create an ObjectType for a Label, the LabelMeta and LabelIndex value included in the label must be brought up.
Since all the data needed to generate the schema is needed only once, the entire data is read in advance and the data is generated.
Since the DB data is all metadata, the size is small, so it does not burden the memory.
It can also help manage the cache's validity cycle by reading the data all at once.
> [S2GRAPH-232] Elimination of inefficiency due to duplication in GraphQL schema generation.

- project/Common.scala
- s2jobs/build.sbt
- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/Job.scala
- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/JobDescription.scala
- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/JobLauncher.scala
- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/task/Sink.scala
- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/udfs/Grok.scala
- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/udfs/Udf.scala
- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/utils/GrokHelper.scala
I simply added udf trait that can be implemented to use custom UDF class.
```
trait Udf extends Serializable with Logger {
def register(ss: SparkSession, name:String, options:Map[String, String])
}
```
If you implement the  *register()* method by inheriting the above udf trait, you can create custom UDF and use it in SQL by specifying the udf in the job description
```
udfs: [
{
name: udf_name
class: org.apache.s2graph.s2jobs.udfs.MyUdfClass
params: {
"param": "dummy"
}
}
]
```
> [S2GRAPH-225] support custom udf class

- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/JobDescription.scala
- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/task/Sink.scala
- s2jobs/src/main/scala/org/apache/s2graph/s2jobs/task/Source.scala
I simply added 'jdbc' options. 
You can create Spark DataFrame from jdbc storage like below example,
```
"source": [
{
"name": "jdbc_storage",
"inputs": [],
"type": "jdbc",
"options": {
"driver": "com.mysql.jdbc.Driver",
"url": "jdbc:mysql://localhost:3306/mydb",
"dbtable": "mytable",
"user": "user",
"password": "password",
"fetchsize": "10"
}
}
]
```
and write from dataframe to jdbc storage.
```
"sink": [
{
"name": "jdbc_sink",
"inputs": [
"my_dataframe"
]
"type": "jdbc",
"options": {
"driver": "com.mysql.jdbc.Driver",
"url": "jdbc:mysql://localhost:3306/mydb",
"dbtable": "mytable",
"user": "user",
"password": "password",
"batchsize": "10",
"mode": "append"
}
}
]
```
Please check the URL below for a list of available options
https://spark.apache.org/docs/latest/sql-data-sources-jdbc.html
> [S2GRAPH-251] add jdbc options 
